/turtlesim:
  ros__parameters:
    background_b: 0
    background_g: 0
    background_r: 0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

    # ros2 param dump /turtlesim --output-dir src/cpp01_launch/config/
